<?php

/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
$modules = array(
	'Application',
);

if (php_sapi_name() == "cli") {
	$env = null;
	$em = null;
	$configGlobPaths = array();

	if (strpos($argv[0], 'doctrine-module') > 0) {
		if ($argv) {
			foreach ($argv as $key => $value) {
				if (strpos($value, '--env') === 0) {
					$env = str_replace('--env=', '', $value);
					unset($argv[$key], $_SERVER['argv'][$key]);
					break;
				}
			}

			foreach ($argv as $key => $value) {
				if (strpos($value, '--em') === 0) {
					$em = str_replace('--em=', '', $value);
					unset($argv[$key], $_SERVER['argv'][$key]);
					break;
				}
			}
		}

		if (!$env) {
			echo "\n======================= ERROR =================================\n\n";
			echo "Missing parameter: --env\n\n";
			echo "Locally use: --env=dev-YOUR_SHORT_NAME\n\n";
			echo "On a server use: --env={dev,test,prod}\n";
			echo "\n===============================================================\n";
			die();
		}

		if (!$em) {
			echo "\n======================= ERROR =================================\n\n";
			echo "Missing parameter: --em\n\n";
			echo "Use: --em=[orm-default, orm-statistic]\n\n";
			echo "\n===============================================================\n";
			die();
		} else {
			if (!file_exists(__DIR__ . '/autoload/' . $env . '/local-' . $em . '.php')) {
				echo "\n======================= ERROR =================================\n\n";
				echo "Missing configuration file: 'config/autoload/" . $env . "/local-" . $em . ".php'\n\n";
				echo "\n===============================================================\n";
				die();
			}

			$configGlobPaths = array(
				'config/autoload/{{,*.}global,{,*.}local}.php',
				'config/autoload/' . $env . '/local-' . $em . '.php',
			);
		}
	}

	if (!strpos($argv[0], 'zftool/zf.php') > 0) {
		$modules[] = 'DoctrineModule';
		$modules[] = 'DoctrineORMModule';
	}
} else {
	$env = APPLICATION_ENV;
	$configGlobPaths = array(
		'config/autoload/{{,*.}global,{,*.}local}.php',
		'config/autoload/' . $env . '/{,*.}{global,local}.php',
	);

	$modules[] = 'DoctrineModule';
	$modules[] = 'DoctrineORMModule';
}

$showZDT = array('dev-paml');
if (in_array($env, $showZDT)) {
//    $modules[] = 'ZendDeveloperTools';
}

return array(
	'modules' => $modules,
	'module_listener_options' => array(
		'module_paths' => array(
			'./module',
			'./vendor',
		),
		'config_glob_paths' => $configGlobPaths,
	),
	'service_manager' => array(
		'factories' => array(
		),
	),
);
