<div class="row" style="padding-top: 50px">
    <div class="col-sm-10">
        <h2>Rośliny</h2>
    </div>
    <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> Dodaj roślinę</button>
    <div class="plants-list">
        <table class='table table-hover'>
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nazwa rośliny</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->plants as $plant): ?>
                    <tr><td><?php echo $plant->getId();?></td><td><?php echo $plant->getName(); ?></td></tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Dodaj roślinę</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="email">Nazwa:</label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control" id="name" placeholder="Wpisz nazwę rośliny">
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                <button type="button" class="btn btn-primary disabled js-save">Zapisz zmiany</button>
            </div>
        </div>
    </div>
</div>
<script>
    $('#name').on('blur', function () {
        $('.js-save').removeClass('disabled').on('click', function (e) {
            $.ajax({
                url: '<?php echo $this->url('save', array('option' => 'plants')); ?>',
                type: 'POST',
                dataType: 'json',
                data: {
                    plantName: $('#name').val()
                },
                success: function (response) {
                    if (response.code == 1) {
                        location.reload();
                    } else {
                        $.toaster({message: 'Nie udało się zapisać rośliny', title: 'Błąd!', priority: 'danger'});
                        $('#myModal').modal('hide');
                    }
                }
            });
            e.preventDefault();
            return false;
        });
    });
</script>
